services:
  app:
    build: .
    container_name: symfony_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      - php -S 0.0.0.0:8000 -t public

  db:
    image: mysql:8
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
